name: Build and deploy Node.js app to Azure Web App - pa4-27100085

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: npm install
        working-directory: ./webapp
        run: npm install

      - name: Zip webapp folder
        run: cd webapp && zip -r ../release.zip . && cd ..

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'pa4-27100085'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREWEBAPPS_PUBLISH_PROFILE }}
          package: release.zip
